### ISSUE TITLE
TODO: close the modal

### ISSUE THREAD

**Issue by alexperronnet** [alexperronnet/openclassrooms-p4-gameon#1]
Add functionality to the close button

**Comment by alexperronnet** [comment]
32943d196daece4c7ce4f3102bdd7b94d8f608e4

**Comment by alexperronnet** [comment]
### Main functionnality added: 

- [x] Close modal when user click on close button

### Optionals:

- [x] Close modal when user click outside
- [x] Close modal when user press ESC key

> See a5706216c66dea5a5f670fe50ba1d311e56f5008 for more informations
